/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ActivityType = IDL.Variant({
  'deposit' : IDL.Null,
  'withdrawal' : IDL.Null,
  'referralBonus' : IDL.Null,
  'interestPayment' : IDL.Null,
});
export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ActivityStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'status' : ActivityStatus,
  'activityType' : ActivityType,
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'gmail' : IDL.Text,
});
export const MarketPrices = IDL.Record({
  'ethPriceUSD' : IDL.Float64,
  'lastUpdated' : Time,
  'btcPriceUSD' : IDL.Float64,
});
export const PlatformStats = IDL.Record({
  'communityMembers' : IDL.Nat,
  'totalUSDBalance' : IDL.Float64,
  'totalBTC' : IDL.Float64,
  'registeredInvestors' : IDL.Nat,
  'featuredBitcoinAddress' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addActivity' : IDL.Func(
      [IDL.Float64, ActivityType, IDL.Text],
      [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : Time })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getActivityById' : IDL.Func([IDL.Nat], [Activity], ['query']),
  'getAllActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMarketPrices' : IDL.Func([], [MarketPrices], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementCommunityMemberCount' : IDL.Func([], [], []),
  'incrementInvestorCount' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateActivityStatus' : IDL.Func([IDL.Nat, ActivityStatus], [Activity], []),
  'updateBitcoinAddress' : IDL.Func([IDL.Text], [], []),
  'updateMarketPrices' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'updateMyUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ActivityType = IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
    'referralBonus' : IDL.Null,
    'interestPayment' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ActivityStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'status' : ActivityStatus,
    'activityType' : ActivityType,
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'gmail' : IDL.Text,
  });
  const MarketPrices = IDL.Record({
    'ethPriceUSD' : IDL.Float64,
    'lastUpdated' : Time,
    'btcPriceUSD' : IDL.Float64,
  });
  const PlatformStats = IDL.Record({
    'communityMembers' : IDL.Nat,
    'totalUSDBalance' : IDL.Float64,
    'totalBTC' : IDL.Float64,
    'registeredInvestors' : IDL.Nat,
    'featuredBitcoinAddress' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addActivity' : IDL.Func(
        [IDL.Float64, ActivityType, IDL.Text],
        [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : Time })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getActivityById' : IDL.Func([IDL.Nat], [Activity], ['query']),
    'getAllActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMarketPrices' : IDL.Func([], [MarketPrices], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementCommunityMemberCount' : IDL.Func([], [], []),
    'incrementInvestorCount' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateActivityStatus' : IDL.Func(
        [IDL.Nat, ActivityStatus],
        [Activity],
        [],
      ),
    'updateBitcoinAddress' : IDL.Func([IDL.Text], [], []),
    'updateMarketPrices' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'updateMyUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  });
};

export const init = ({ IDL }) => { return []; };