/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ActivityType = IDL.Variant({
  'loginFailed' : IDL.Null,
  'settingsChange' : IDL.Null,
  'receiveMoney' : IDL.Null,
  'accountCreation' : IDL.Null,
  'deposit' : IDL.Null,
  'login' : IDL.Null,
  'withdrawal' : IDL.Null,
  'keyVerification' : IDL.Null,
  'sendMoney' : IDL.Null,
  'receiptUpload' : IDL.Null,
  'referralBonus' : IDL.Null,
  'interestPayment' : IDL.Null,
});
export const Time = IDL.Int;
export const ActivityStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'status' : ActivityStatus,
  'activityType' : ActivityType,
  'username' : IDL.Text,
  'userGmail' : IDL.Text,
  'reference' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'sessionId' : IDL.Text,
  'amount' : IDL.Float64,
});
export const ActivityStats = IDL.Record({
  'totalActivities' : IDL.Nat,
  'totalLogins' : IDL.Nat,
  'failedLogins' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalDeposits' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'gmail' : IDL.Text,
  'isAdmin' : IDL.Bool,
});
export const MarketPrices = IDL.Record({
  'ethPriceUSD' : IDL.Float64,
  'lastUpdated' : Time,
  'btcPriceUSD' : IDL.Float64,
});
export const PlatformStats = IDL.Record({
  'communityMembers' : IDL.Nat,
  'totalUSDBalance' : IDL.Float64,
  'totalBTC' : IDL.Float64,
  'registeredInvestors' : IDL.Nat,
  'featuredBitcoinAddress' : IDL.Text,
});

export const idlService = IDL.Service({
  'addActivity' : IDL.Func(
      [IDL.Float64, ActivityType, IDL.Text],
      [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : Time })],
      [],
    ),
  'getActivityById' : IDL.Func([IDL.Nat], [IDL.Opt(Activity)], ['query']),
  'getActivityStats' : IDL.Func([], [ActivityStats], ['query']),
  'getAllActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getAllUserActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMarketPrices' : IDL.Func([], [MarketPrices], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getUserActivitiesByGmail' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementCommunityMemberCount' : IDL.Func([], [], []),
  'incrementInvestorCount' : IDL.Func([], [], []),
  'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
  'logUserAction' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ActivityType,
        IDL.Opt(IDL.Float64),
        IDL.Text,
        IDL.Opt(IDL.Text),
        ActivityStatus,
      ],
      [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : Time })],
      [],
    ),
  'registerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminRole' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'updateActivityStatus' : IDL.Func(
      [IDL.Nat, ActivityStatus],
      [IDL.Opt(Activity)],
      [],
    ),
  'updateBitcoinAddress' : IDL.Func([IDL.Text], [], []),
  'updateMarketPrices' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'updateMyUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(UserProfile)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ActivityType = IDL.Variant({
    'loginFailed' : IDL.Null,
    'settingsChange' : IDL.Null,
    'receiveMoney' : IDL.Null,
    'accountCreation' : IDL.Null,
    'deposit' : IDL.Null,
    'login' : IDL.Null,
    'withdrawal' : IDL.Null,
    'keyVerification' : IDL.Null,
    'sendMoney' : IDL.Null,
    'receiptUpload' : IDL.Null,
    'referralBonus' : IDL.Null,
    'interestPayment' : IDL.Null,
  });
  const Time = IDL.Int;
  const ActivityStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'status' : ActivityStatus,
    'activityType' : ActivityType,
    'username' : IDL.Text,
    'userGmail' : IDL.Text,
    'reference' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'sessionId' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const ActivityStats = IDL.Record({
    'totalActivities' : IDL.Nat,
    'totalLogins' : IDL.Nat,
    'failedLogins' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalDeposits' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'gmail' : IDL.Text,
    'isAdmin' : IDL.Bool,
  });
  const MarketPrices = IDL.Record({
    'ethPriceUSD' : IDL.Float64,
    'lastUpdated' : Time,
    'btcPriceUSD' : IDL.Float64,
  });
  const PlatformStats = IDL.Record({
    'communityMembers' : IDL.Nat,
    'totalUSDBalance' : IDL.Float64,
    'totalBTC' : IDL.Float64,
    'registeredInvestors' : IDL.Nat,
    'featuredBitcoinAddress' : IDL.Text,
  });
  
  return IDL.Service({
    'addActivity' : IDL.Func(
        [IDL.Float64, ActivityType, IDL.Text],
        [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : Time })],
        [],
      ),
    'getActivityById' : IDL.Func([IDL.Nat], [IDL.Opt(Activity)], ['query']),
    'getActivityStats' : IDL.Func([], [ActivityStats], ['query']),
    'getAllActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getAllUserActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMarketPrices' : IDL.Func([], [MarketPrices], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getUserActivitiesByGmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementCommunityMemberCount' : IDL.Func([], [], []),
    'incrementInvestorCount' : IDL.Func([], [], []),
    'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
    'logUserAction' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ActivityType,
          IDL.Opt(IDL.Float64),
          IDL.Text,
          IDL.Opt(IDL.Text),
          ActivityStatus,
        ],
        [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : Time })],
        [],
      ),
    'registerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminRole' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'updateActivityStatus' : IDL.Func(
        [IDL.Nat, ActivityStatus],
        [IDL.Opt(Activity)],
        [],
      ),
    'updateBitcoinAddress' : IDL.Func([IDL.Text], [], []),
    'updateMarketPrices' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'updateMyUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(UserProfile)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };