/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'status' : ActivityStatus,
  'activityType' : ActivityType,
  'username' : string,
  'userGmail' : string,
  'reference' : string,
  'description' : string,
  'timestamp' : Time,
  'sessionId' : string,
  'amount' : number,
}
export interface ActivityStats {
  'totalActivities' : bigint,
  'totalLogins' : bigint,
  'failedLogins' : bigint,
  'totalUsers' : bigint,
  'totalDeposits' : bigint,
}
export type ActivityStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type ActivityType = { 'loginFailed' : null } |
  { 'settingsChange' : null } |
  { 'receiveMoney' : null } |
  { 'accountCreation' : null } |
  { 'deposit' : null } |
  { 'login' : null } |
  { 'withdrawal' : null } |
  { 'keyVerification' : null } |
  { 'sendMoney' : null } |
  { 'receiptUpload' : null } |
  { 'referralBonus' : null } |
  { 'interestPayment' : null };
export interface MarketPrices {
  'ethPriceUSD' : number,
  'lastUpdated' : Time,
  'btcPriceUSD' : number,
}
export interface PlatformStats {
  'communityMembers' : bigint,
  'totalUSDBalance' : number,
  'totalBTC' : number,
  'registeredInvestors' : bigint,
  'featuredBitcoinAddress' : string,
}
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'displayName' : string,
  'gmail' : string,
  'isAdmin' : boolean,
}
export interface _SERVICE {
  'addActivity' : ActorMethod<
    [number, ActivityType, string],
    { 'id' : bigint, 'timestamp' : Time }
  >,
  'getActivityById' : ActorMethod<[bigint], [] | [Activity]>,
  'getActivityStats' : ActorMethod<[], ActivityStats>,
  'getAllActivities' : ActorMethod<[], Array<Activity>>,
  'getAllUserActivities' : ActorMethod<[], Array<Activity>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMarketPrices' : ActorMethod<[], MarketPrices>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getUserActivitiesByGmail' : ActorMethod<[string], Array<Activity>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementCommunityMemberCount' : ActorMethod<[], undefined>,
  'incrementInvestorCount' : ActorMethod<[], undefined>,
  'isAdminCaller' : ActorMethod<[], boolean>,
  'logUserAction' : ActorMethod<
    [
      string,
      string,
      ActivityType,
      [] | [number],
      string,
      [] | [string],
      ActivityStatus,
    ],
    { 'id' : bigint, 'timestamp' : Time }
  >,
  'registerUserProfile' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminRole' : ActorMethod<[Principal, boolean], undefined>,
  'updateActivityStatus' : ActorMethod<
    [bigint, ActivityStatus],
    [] | [Activity]
  >,
  'updateBitcoinAddress' : ActorMethod<[string], undefined>,
  'updateMarketPrices' : ActorMethod<[number, number], undefined>,
  'updateMyUserProfile' : ActorMethod<[string, string], [] | [UserProfile]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];