/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'status' : ActivityStatus,
  'activityType' : ActivityType,
  'description' : string,
  'timestamp' : Time,
  'amount' : number,
}
export type ActivityStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type ActivityType = { 'deposit' : null } |
  { 'withdrawal' : null } |
  { 'referralBonus' : null } |
  { 'interestPayment' : null };
export interface MarketPrices {
  'ethPriceUSD' : number,
  'lastUpdated' : Time,
  'btcPriceUSD' : number,
}
export interface PlatformStats {
  'communityMembers' : bigint,
  'totalUSDBalance' : number,
  'totalBTC' : number,
  'registeredInvestors' : bigint,
  'featuredBitcoinAddress' : string,
}
export type Time = bigint;
export interface UserProfile { 'displayName' : string, 'gmail' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addActivity' : ActorMethod<
    [number, ActivityType, string],
    { 'id' : bigint, 'timestamp' : Time }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getActivityById' : ActorMethod<[bigint], Activity>,
  'getAllActivities' : ActorMethod<[], Array<Activity>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMarketPrices' : ActorMethod<[], MarketPrices>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementCommunityMemberCount' : ActorMethod<[], undefined>,
  'incrementInvestorCount' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUserProfile' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateActivityStatus' : ActorMethod<[bigint, ActivityStatus], Activity>,
  'updateBitcoinAddress' : ActorMethod<[string], undefined>,
  'updateMarketPrices' : ActorMethod<[number, number], undefined>,
  'updateMyUserProfile' : ActorMethod<[string, string], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];