/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ActivityStats {
    totalActivities: bigint;
    totalLogins: bigint;
    failedLogins: bigint;
    totalUsers: bigint;
    totalDeposits: bigint;
}
export type Time = bigint;
export interface Activity {
    id: bigint;
    status: ActivityStatus;
    activityType: ActivityType;
    username: string;
    userGmail: string;
    reference: string;
    description: string;
    timestamp: Time;
    sessionId: string;
    amount: number;
}
export interface MarketPrices {
    ethPriceUSD: number;
    lastUpdated: Time;
    btcPriceUSD: number;
}
export interface PlatformStats {
    communityMembers: bigint;
    totalUSDBalance: number;
    totalBTC: number;
    registeredInvestors: bigint;
    featuredBitcoinAddress: string;
}
export interface UserProfile {
    username: string;
    displayName: string;
    gmail: string;
    isAdmin: boolean;
}
export enum ActivityStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum ActivityType {
    loginFailed = "loginFailed",
    settingsChange = "settingsChange",
    receiveMoney = "receiveMoney",
    accountCreation = "accountCreation",
    deposit = "deposit",
    login = "login",
    withdrawal = "withdrawal",
    keyVerification = "keyVerification",
    sendMoney = "sendMoney",
    receiptUpload = "receiptUpload",
    referralBonus = "referralBonus",
    interestPayment = "interestPayment"
}
export interface backendInterface {
    addActivity(amount: number, activityType: ActivityType, description: string): Promise<{
        id: bigint;
        timestamp: Time;
    }>;
    getActivityById(activityId: bigint): Promise<Activity | null>;
    getActivityStats(): Promise<ActivityStats>;
    getAllActivities(): Promise<Array<Activity>>;
    getAllUserActivities(): Promise<Array<Activity>>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getMarketPrices(): Promise<MarketPrices>;
    getPlatformStats(): Promise<PlatformStats>;
    getUserActivitiesByGmail(gmail: string): Promise<Array<Activity>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    incrementCommunityMemberCount(): Promise<void>;
    incrementInvestorCount(): Promise<void>;
    isAdminCaller(): Promise<boolean>;
    logUserAction(gmail: string, username: string, activityType: ActivityType, amount: number | null, description: string, reference: string | null, status: ActivityStatus): Promise<{
        id: bigint;
        timestamp: Time;
    }>;
    registerUserProfile(displayName: string, gmail: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAdminRole(target: Principal, makeAdmin: boolean): Promise<void>;
    updateActivityStatus(activityId: bigint, newStatus: ActivityStatus): Promise<Activity | null>;
    updateBitcoinAddress(newAddress: string): Promise<void>;
    updateMarketPrices(btcPrice: number, ethPrice: number): Promise<void>;
    updateMyUserProfile(displayName: string, gmail: string): Promise<UserProfile | null>;
}
import type { Activity as _Activity, ActivityStatus as _ActivityStatus, ActivityType as _ActivityType, Time as _Time, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addActivity(arg0: number, arg1: ActivityType, arg2: string): Promise<{
        id: bigint;
        timestamp: Time;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivity(arg0, to_candid_ActivityType_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivity(arg0, to_candid_ActivityType_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async getActivityById(arg0: bigint): Promise<Activity | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityById(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityById(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityStats(): Promise<ActivityStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityStats();
            return result;
        }
    }
    async getAllActivities(): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActivities();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActivities();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserActivities(): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserActivities();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserActivities();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketPrices(): Promise<MarketPrices> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketPrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketPrices();
            return result;
        }
    }
    async getPlatformStats(): Promise<PlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getUserActivitiesByGmail(arg0: string): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserActivitiesByGmail(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserActivitiesByGmail(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementCommunityMemberCount(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementCommunityMemberCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementCommunityMemberCount();
            return result;
        }
    }
    async incrementInvestorCount(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementInvestorCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementInvestorCount();
            return result;
        }
    }
    async isAdminCaller(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminCaller();
            return result;
        }
    }
    async logUserAction(arg0: string, arg1: string, arg2: ActivityType, arg3: number | null, arg4: string, arg5: string | null, arg6: ActivityStatus): Promise<{
        id: bigint;
        timestamp: Time;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.logUserAction(arg0, arg1, to_candid_ActivityType_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5), to_candid_ActivityStatus_n14(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logUserAction(arg0, arg1, to_candid_ActivityType_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5), to_candid_ActivityStatus_n14(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async registerUserProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUserProfile(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAdminRole(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminRole(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminRole(arg0, arg1);
            return result;
        }
    }
    async updateActivityStatus(arg0: bigint, arg1: ActivityStatus): Promise<Activity | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivityStatus(arg0, to_candid_ActivityStatus_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivityStatus(arg0, to_candid_ActivityStatus_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBitcoinAddress(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBitcoinAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBitcoinAddress(arg0);
            return result;
        }
    }
    async updateMarketPrices(arg0: number, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMarketPrices(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMarketPrices(arg0, arg1);
            return result;
        }
    }
    async updateMyUserProfile(arg0: string, arg1: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyUserProfile(arg0, arg1);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyUserProfile(arg0, arg1);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActivityStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityStatus): ActivityStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Activity_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Activity]): Activity | null {
    return value.length === 0 ? null : from_candid_Activity_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ActivityStatus;
    activityType: _ActivityType;
    username: string;
    userGmail: string;
    reference: string;
    description: string;
    timestamp: _Time;
    sessionId: string;
    amount: number;
}): {
    id: bigint;
    status: ActivityStatus;
    activityType: ActivityType;
    username: string;
    userGmail: string;
    reference: string;
    description: string;
    timestamp: Time;
    sessionId: string;
    amount: number;
} {
    return {
        id: value.id,
        status: from_candid_ActivityStatus_n6(_uploadFile, _downloadFile, value.status),
        activityType: from_candid_ActivityType_n8(_uploadFile, _downloadFile, value.activityType),
        username: value.username,
        userGmail: value.userGmail,
        reference: value.reference,
        description: value.description,
        timestamp: value.timestamp,
        sessionId: value.sessionId,
        amount: value.amount
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): ActivityStatus {
    return "pending" in value ? ActivityStatus.pending : "completed" in value ? ActivityStatus.completed : "failed" in value ? ActivityStatus.failed : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loginFailed: null;
} | {
    settingsChange: null;
} | {
    receiveMoney: null;
} | {
    accountCreation: null;
} | {
    deposit: null;
} | {
    login: null;
} | {
    withdrawal: null;
} | {
    keyVerification: null;
} | {
    sendMoney: null;
} | {
    receiptUpload: null;
} | {
    referralBonus: null;
} | {
    interestPayment: null;
}): ActivityType {
    return "loginFailed" in value ? ActivityType.loginFailed : "settingsChange" in value ? ActivityType.settingsChange : "receiveMoney" in value ? ActivityType.receiveMoney : "accountCreation" in value ? ActivityType.accountCreation : "deposit" in value ? ActivityType.deposit : "login" in value ? ActivityType.login : "withdrawal" in value ? ActivityType.withdrawal : "keyVerification" in value ? ActivityType.keyVerification : "sendMoney" in value ? ActivityType.sendMoney : "receiptUpload" in value ? ActivityType.receiptUpload : "referralBonus" in value ? ActivityType.referralBonus : "interestPayment" in value ? ActivityType.interestPayment : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n4(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityStatus): _ActivityStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_ActivityType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): _ActivityType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityStatus): {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
} {
    return value == ActivityStatus.pending ? {
        pending: null
    } : value == ActivityStatus.completed ? {
        completed: null
    } : value == ActivityStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): {
    loginFailed: null;
} | {
    settingsChange: null;
} | {
    receiveMoney: null;
} | {
    accountCreation: null;
} | {
    deposit: null;
} | {
    login: null;
} | {
    withdrawal: null;
} | {
    keyVerification: null;
} | {
    sendMoney: null;
} | {
    receiptUpload: null;
} | {
    referralBonus: null;
} | {
    interestPayment: null;
} {
    return value == ActivityType.loginFailed ? {
        loginFailed: null
    } : value == ActivityType.settingsChange ? {
        settingsChange: null
    } : value == ActivityType.receiveMoney ? {
        receiveMoney: null
    } : value == ActivityType.accountCreation ? {
        accountCreation: null
    } : value == ActivityType.deposit ? {
        deposit: null
    } : value == ActivityType.login ? {
        login: null
    } : value == ActivityType.withdrawal ? {
        withdrawal: null
    } : value == ActivityType.keyVerification ? {
        keyVerification: null
    } : value == ActivityType.sendMoney ? {
        sendMoney: null
    } : value == ActivityType.receiptUpload ? {
        receiptUpload: null
    } : value == ActivityType.referralBonus ? {
        referralBonus: null
    } : value == ActivityType.interestPayment ? {
        interestPayment: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
